### ISSUE TITLE
Add "max-distance to waypoint" option

### ISSUE THREAD

**Issue by rambo** [rambo/arma3_missions#4]
Feature-request from the comments:

> rambo I have no idea how to script so I can't modify the files myself but would it be possible to add LZ max distance to the parameters? I've added your scripts to a jungle map but some of the LZs are upwards of 9km from each other and then it becomes flying trainer instead of landing trainer. Other than that, awesome mission though

**Comment by mija** [comment]
change your SelectLZ to this:

```
params [["_excludeList", []]];

private _candidates = lzList;

if (_excludeList isEqualType []) then 
{ 
	_candidates = _candidates - _excludeList;
};

private _taskLocations = [west] call getSideActiveTasks apply { [_x] call BIS_fnc_taskDestination };

for "_i" from 0 to LZCOUNT do {
    private _candidate = selectRandom _candidates;
    if (_taskLocations findIf { _x distance _candidate < LZMinDistace } == -1 && { allPlayers findIf { _x distance _candidate > LZMaxDistace } == -1 }) exitWith { _candidate };
    false
}
```

add a Max Distance param so it is tweakable just like LzMinDistace thing. this will work with max distance to waypoint.
I also suggest changing your createSquad.sqf to this:

```
//diag_log format["createSquad called, _this: %1", _this];
private _spawnPos = _this select 0;

_veh = typeOf (vehicle player);
_totalSeats = [_veh, true] call BIS_fnc_crewCount;
_crewSeats = [_veh, false] call BIS_fnc_crewCount;
_cargoSeats = _totalSeats - _crewSeats;

// TODO: use some preconfigured fireteam setup
private _groupTaxi = createGroup west;
"vn_b_men_sog_22" createUnit [_spawnPos, _groupTaxi,"",0.6, "CORPORAL"];

for "_i" from 1 to (_cargoSeats - 1) do {
"vn_b_men_sog_05" createUnit [_spawnPos, _groupTaxi,"",0.5, "PRIVATE"];
 };

_groupTaxi
```

This will make sure to not spawn more units to pick up than the helicopter can load.
Another quick thing I would change is to modify your spawnCrewAction.sqf to this:

```
//diag_log format["spawnCrewAction called, _this: %1", _this];
private _vehicle = _this select 0;
private _caller = _this select 1;
private _returnValue = [];
private _group = group _caller;
private _tmpGroup = createGroup civilian;
_returnValue = [ _vehicle, _tmpGroup, false, typeof _vehicle]; createVehicleCrew _vehicle; _vehicle deleteVehicleCrew driver _vehicle;
// a bit of twiddling to get the units to the correct side
_returnValue joinSilent grpNull;
_returnValue joinSilent _group;
deleteGroup _tmpGroup;

//diag_log format["spawnCrewAction returning: %1", _returnValue];
_returnValue
```

this will prevent FFV seats from being filled with crew, preventing units you are picking up from mounting. (will only fill copilot+turrets).

I'd probably add a removeCrewAction and add that to vehicleinit too so you can delete crewmembers if you want to, for whatever reason.
