### ISSUE TITLE
Make it possible to place LZ markers on roofs

### ISSUE THREAD

**Issue by rambo** [rambo/arma3_missions#6]
from @mija
````
if you change getPos to getPosATL in createPickupLZ and createDropoffLZ then update isLanded to use getPos instead of getPosATL its possible to place landingzones on roofs of buildings.

as it stands without those changes the LZ will spawn below the building at terrain level
````

**Comment by mija** [comment]
in  vehicleinit.sqf if you add "`,nil,1.5,true,true,"","true",5,false,"",""`" to the addAction it will limit the range of the action to 5 meters. This makes the start area feel less bloated as if youre inside of a heli and looking towards another you will get multiple instances of the commands appear (assuming the other heli is within 50 meters, which is the default radius).

this is an example of how it would look like changed:

`[_vehicle, ["Destroy tail rotor", { _this remoteExec ["destroyTailrotorAction", _this select 0]; },nil,1.5,true,true,"","true",5,false,"",""]] remoteExec ["addAction", 0, "atrotdestroy" + (_vehicle call BIS_fnc_netId)];`

the 5 can ofc be set higher but the default 50 meters feels a bit excessive to me.

i would probably also remove the repair command and instead tie that to a service area trigger you land on that services and refuels your vehicle, getting rid of the fuel truck thats there right now and simple have an area with a trigger that runs the xenoRepair when landed there. thats not really a bug fix though but rather a matter of taste change.

oh and you can add a parameter looking something like this:

```
		title = "Enemy distance from LZ";
		values[] = {100,200,300,400};
		texts[] = {"100-200m", "100-300m", "100-400m", "100-600m"};
		default = 300;
```

and then edit this part in createEnemySquad.sqf:

```
// Some variance
private _centreCoords = getPos _centrePos;
_centreCoords set [0, ((_centreCoords select 0) + 100 + (floor random 300))];
_centreCoords set [1, ((_centreCoords select 1) + 100 + (floor random 300))];
```

to this:

```
// Some variance
private _centreCoords = getPos _centrePos;
_centreCoords set [0, ((_centreCoords select 0) + 100 + (floor random enemyDistace))];
_centreCoords set [1, ((_centreCoords select 1) + 100 + (floor random enemyDistace))];
```

then players can make the hostile spawn closer to LZ making it tougher. i guess one could also change the 100 value to allow players to determine minimum and maximum distance.

**Comment by mija** [comment]
I guess setting it up like this makes more sense actually:

```
// Some variance
private _centreCoords = getPos _centrePos;
_centreCoords set [0, ((_centreCoords select 0) + enemyDistace + (floor random 100))];
_centreCoords set [1, ((_centreCoords select 1) + enemyDistace + (floor random 100))];
```

**Comment by mija** [comment]
should all be addressed in the pullrequest.
